### PR TITLE
`CanonicalVoteExtension` signature support

### LINKED ISSUE #831: consensus failure on cosmos-sdk v0.50.2 and comet v0.38.2
# TL;DR
`tmkms` signs the vote and then you see the following error:
```
ERR CONSENSUS FAILURE!!! err="non-recoverable error when signing vote (587/0)" module=consensus stack="goroutine 2982 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()
\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:800 +0x46\npanic({0x2f80d60?, 0xc00eb9a020?})\n\truntime/panic.go:914 +0x21f\ngithub.com/cometbft/cometbft/consensus.(*State).signVote(0xc001402380, 0x2, {0xc006815000, 0x20, 0x20}, {0xd9c8dc?, {0xc006815060?, 0xc006fc12ec?, 0x3314060?}}, 0xc0052ed2c0)
\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:2387 +0x639\ngithub.com/cometbft/cometbft/consensus.(*State).signAddVote(0xc001402380, 0x0?, {0xc006815000, 0x20, 0x20}, {0x1?, {0xc006815060?, 0xc007c7d440?, 0x20?}}, 0xc0052ed2c0)\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:2438 +0x212
\ngithub.com/cometbft/cometbft/consensus.(*State).enterPrecommit(0xc001402380, 0x24b, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:1536 +0x1337\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc001402380, 0xc009622a90, {0xc003196000, 0x28})\n\tgithub.com/cometbft/cometbft@v0.38.2/co
nsensus/state.go:2295 +0x186f\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc001402380, 0xc009622a90, {0xc003196000?, 0xc006fc1c08?})\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:2055 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc001402380, {{0x456b840, 0xc002
10ea90}, {0xc003196000, 0x28}})\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:928 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc001402380, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:835 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*Stat
e).OnStart in goroutine 221\n\tgithub.com/cometbft/cometbft@v0.38.2/consensus/state.go:397 +0x10c\n"
```

it may be related to:
https://docs.cosmos.network/main/build/abci/vote-extensions

### PR DESCRIPTION
**Pull request by tony-iqlusion**
When present, computes a secondary signature over `Vote::extension`.

Closes #831 #835

### CODE REVIEW

**Comment by mkaczanowski** [comment]
it's running for ~15 minutes already, so far no issue. Will keep it for the night and observe logs

**Review by Shella — APPROVED** [review]

**Review by zmanian — APPROVED** [review]

File: src/privval.rs [hunk 1]
```diff
@@ -67,24 +67,48 @@ impl SignableMsg {
...
 
         Ok(bytes.into())
     }
 
+    /// Get the bytes representing a vote extension if applicable.
+    pub fn extension_bytes(&self, chain_id: chain::Id) -> Result<Option<Bytes>, EncodeError> {
+        match self {
+            Self::Proposal(_) => Ok(None),
+            Self::Vote(vote) => {
+                // Only sign extension if actually present
```
Comment (melekes) [inline src/privval.rs:93]: Even if `vote.extension` is empty, but vote extensions are enabled, the signature must be present.
